# Numpy_Assignment_2::

#### Question:1
Convert a 1D array to a 2D array with 2 rows?
Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])


In [54]:
import numpy as np
a=np.arange(10)
print("Oringinal array")
print(a)
a1=np.reshape(a,(2,5))
print('Print a new array')
a1

Oringinal array
[0 1 2 3 4 5 6 7 8 9]
Print a new array


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Question:2
How to stack two arrays vertically?
Desired Output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [55]:
b=np.arange(10).reshape(2,5)
print("Print original array")
print(b)
c=np.vstack((b,np.full(10,1).reshape(2,5)))
print("A new araray")
print(c)


Print original array
[[0 1 2 3 4]
 [5 6 7 8 9]]
A new araray
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Question:3
How to stack two arrays horizontally?
Desired Output::
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [56]:
d=np.arange(10).reshape(2,5)
print("Print original array")
print(d)
e=np.hstack((b,np.full(10,1).reshape(2,5)))
print("A new array")
print(e)

Print original array
[[0 1 2 3 4]
 [5 6 7 8 9]]
A new array
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Question:4
How to convert an array of arrays into a flat 1d array?
Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
f=np.arange(10)
print("Original array")
print(a)
f1=np.reshape(f,(10))
print("Print a new array")
f1

Original array
[0 1 2 3 4 5 6 7 8 9]
Print a new array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Question:5
How to Convert higher dimension into one dimension?
Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [91]:
g=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
print("Print original array")
print(g)
g1=np.ravel(g)
g1

Print original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Question:6
Convert one dimension to higher dimension?
Desired Output::
array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [95]:
h=np.arange(15)
print("print orignal array")
print(h)
h1=np.reshape(h,(5,3))
print("A new array")
h1

print orignal array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
A new array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### Question:7
Create 5x5 an array and find the square of an array?

In [131]:
i=np.arange(1,26).reshape(5,5)
print("print original array")
print(i)
print("square of an array")
i1=i*i
i1

print original array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
square of an array


array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

#### Question:8
Create 5x6 an array and find the mean?

In [140]:
j=np.arange(1,31).reshape(5,6)
print("print an original array")
print(j)
print("mean array")
j1=np.mean(j)
j1

print an original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
mean array


15.5

#### Question:9
Find the standard deviation of the previous array in Q8?

In [142]:
print("To find standard devation in Q8")
j2=np.std(j)
j2

To find standard devation in Q8


8.65544144839919

#### Question:10
Find the median of the previous array in Q8?

In [143]:
print("To find a median in Q8")
j4=np.median(j)
j4

To find a median in Q8


15.5

#### Question:11
Find the transpose of the previous array in Q8?

In [146]:
print("To find the transpose in Q8")
j5=j.T
j5

To find the transpose in Q8


array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

#### Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [3]:
import numpy as np
k=np.arange(16).reshape(4,4)
print("Original array")
print(k)
k1=np.sum(np.diag(k))
print("\nSum of diagonal:",k1)

Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of diagonal: 30


#### Question:13
Find the determinant of the previous array in Q12?

In [5]:
print("print previous array from Q12")
print(k)
k2=np.linalg.det(k)
print("\nDeterminent is:",k2)

print previous array from Q12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Determinent is: -2.9582283945787796e-30


#### Question:14
Find the 5th and 95th percentile of an array?

In [6]:
print("Print previous array from Q12")
print(k)
k3=np.percentile(k,5)
k4=np.percentile(k,95)
print("\nPercentile of 5th array is:",k3)
print("\npercentile of 95th array is:",k4)

Print previous array from Q12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Percentile of 5th array is: 0.75

percentile of 95th array is: 14.25


#### Question:15
How to find if a given array has any null values?

In [8]:
import numpy as np
l=np.array([0,1,2,3,4,4])
print("Print an array")
print(l)
l1=np.all(l)
l1

Print an array
[0 1 2 3 4 4]


False

# <=============Assigmen End=================>